name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

env:
  saludo: Hola perro


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Test actions"
        run: echo ${{ env.saludo }}

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Display context information
        run: |
          echo "The push was made by ${{ github.actor }}"
          echo "Event name: ${{ github.event_name }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Reference: ${{ github.ref }}"
          echo "Repository: ${{ github.repository }}"
      - name: Get user details
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            USER_FULL_NAME=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/users/${{ github.actor }} \
            | jq '.name')
    