name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

env:
  saludo: Hola perro


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Test actions"
        run: echo ${{ env.saludo }}
