name: Ejemplo de GitHub Actions

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment (PD, QA, DEV)'
        required: true
        default: 'DEV'
        type: choice
        options:
          - DEV
          - QA
          - PD
      country:
        description: 'Country code'
        required: true
        default: 'COL'
        type: choice
        options:
          - COL
          - MEX
          - PER
          - CHL

permissions:
  contents: write

jobs:
  test-tag-creation:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    
    - name: Create GitHub tag
      run: |
        TAG_NAME="Test-${{ inputs.env }}-${{ inputs.country }}"
        
        echo "🔎 Verificando si existe el tag $TAG_NAME en remoto..."
        if git ls-remote --tags origin | grep -q "refs/tags/$TAG_NAME$"; then
          echo "⚠️ El tag $TAG_NAME ya existe en GitHub." | tee -a $GITHUB_STEP_SUMMARY
        else
          echo "✅ Creando release con el tag $TAG_NAME..."
          gh release create "$TAG_NAME" \
            --target "$(git rev-parse HEAD)" \
            --title "Release $TAG_NAME" \
            --notes "Automatic release via GitHub Actions"
    
          echo "🎉 Se creó correctamente el release con el tag $TAG_NAME" | tee -a $GITHUB_STEP_SUMMARY
        fi
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
