name: Ejemplo de GitHub Actions

on:
  push:
    branches:
      - main
  workflow_dispatch: # comentario

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Paso 1
        run: echo "Este es el trabajo 1"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Paso 1
        run: echo "Este es el trabajo 2"

  job3:
    runs-on: ubuntu-latest
    steps:
      - name: Paso 1
        run: echo "Este es el trabajo 3"
      - name: Fallar intencionalmente
        run: exit 1

  job4:
    needs: [job1, job2]
    if: ${{ always() && success('job3') }}
    runs-on: ubuntu-latest
    steps:
      - name: Paso 1
        run: echo "Este es el trabajo 4"

