name: Ejemplo de GitHub Actions

on:  
  workflow_dispatch: #

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Paso 1
        run: echo "Este es el Build"
      - name: Fallar intencionalmente
        run: exit 1

  Test-01:
    runs-on: ubuntu-latest
    steps:
      - name: Paso 1
        run: echo "Este es el Test 01"

  Test-02:
    runs-on: ubuntu-latest
    steps:
      - name: Paso 1
        run: echo "Este es el Test 02"

  Deploy:
    needs: [Test-01, Test-02]
    if: ${{ always() && success('Build') }}
    runs-on: ubuntu-latest
    steps:
      - name: Paso 1
        run: echo "Este es el trabajo 4"

